package commands

import (
	"github.com/spf13/cobra"

	"github.com/unstablemind/pocket/pkg/output"
)

// Cmd represents a command for LLM consumption
type Cmd struct {
	Command string `json:"cmd"`
	Desc    string `json:"desc"`
	Args    string `json:"args,omitempty"`
	Flags   string `json:"flags,omitempty"`
}

// Group represents a command group
type Group struct {
	Name     string `json:"name"`
	Commands []Cmd  `json:"commands"`
}

func NewCommandsCmd() *cobra.Command {
	var group string

	cmd := &cobra.Command{
		Use:     "commands",
		Aliases: []string{"cmds", "ls"},
		Short:   "List all commands (LLM-friendly)",
		RunE: func(cmd *cobra.Command, args []string) error {
			all := getAllCommands()

			if group != "" {
				for _, g := range all {
					if g.Name == group {
						return output.Print(g.Commands)
					}
				}
				return output.PrintError("not_found", "group not found", nil)
			}

			return output.Print(all)
		},
	}

	cmd.Flags().StringVarP(&group, "group", "g", "", "Filter by group: social, comms, dev, productivity, news, knowledge, utility, system, security, marketing")

	return cmd
}

func getAllCommands() []Group {
	return []Group{
		{
			Name: "social",
			Commands: []Cmd{
				{Command: "pocket social twitter post", Desc: "Post a tweet (free tier: 1,500/mo)", Args: "[message]", Flags: "--reply-to"},
				{Command: "pocket social twitter delete", Desc: "Delete a tweet", Args: "[tweet-id]"},
				{Command: "pocket social twitter me", Desc: "Get your account info"},
				{Command: "pocket social reddit feed", Desc: "Get your home feed", Flags: "-l limit, -s sort"},
				{Command: "pocket social reddit subreddit", Desc: "Get subreddit posts", Args: "[name]", Flags: "-l limit, -s sort, -t time"},
				{Command: "pocket social reddit search", Desc: "Search Reddit", Args: "[query]", Flags: "-l limit, -r subreddit, -s sort"},
				{Command: "pocket social reddit user", Desc: "Get user info and posts", Args: "[username]", Flags: "-l limit"},
				{Command: "pocket social reddit comments", Desc: "Get post comments", Args: "[post-id]", Flags: "-l limit, -s sort"},
				{Command: "pocket social mastodon timeline", Desc: "Get timeline", Flags: "-l limit, -t type"},
				{Command: "pocket social mastodon post", Desc: "Post a toot", Args: "[content]", Flags: "-V visibility"},
				{Command: "pocket social mastodon search", Desc: "Search Mastodon", Args: "[query]", Flags: "-l limit, -t type"},
				{Command: "pocket social youtube search", Desc: "Search videos", Args: "[query]", Flags: "-l limit, -s order, -a after, -d duration"},
				{Command: "pocket social youtube video", Desc: "Get video details", Args: "[id]"},
				{Command: "pocket social youtube channel", Desc: "Get channel info", Args: "[id-or-handle]"},
				{Command: "pocket social youtube videos", Desc: "List channel videos", Args: "[channel-id]", Flags: "-l limit"},
				{Command: "pocket social youtube comments", Desc: "Get video comments", Args: "[video-id]", Flags: "-l limit, -s order"},
				{Command: "pocket social youtube trending", Desc: "Get trending videos", Flags: "-l limit, -r region, -c category"},
				{Command: "pocket social spotify search", Desc: "Search tracks/artists/albums", Args: "[query]", Flags: "-t type, -l limit"},
				{Command: "pocket social spotify track", Desc: "Get track details", Args: "[id]"},
				{Command: "pocket social spotify artist", Desc: "Get artist details", Args: "[id]"},
				{Command: "pocket social spotify album", Desc: "Get album details", Args: "[id]"},
			},
		},
		{
			Name: "comms",
			Commands: []Cmd{
				{Command: "pocket comms email list", Desc: "List emails", Flags: "-l limit, -m mailbox"},
				{Command: "pocket comms email read", Desc: "Read an email", Args: "[uid]", Flags: "-m mailbox"},
				{Command: "pocket comms email send", Desc: "Send an email", Args: "[body]", Flags: "--to, --subject, --cc"},
				{Command: "pocket comms email reply", Desc: "Reply to an email", Args: "[uid] [body]", Flags: "-m mailbox, -a reply-all"},
				{Command: "pocket comms email search", Desc: "Search emails", Args: "[query]", Flags: "-l limit, -m mailbox"},
				{Command: "pocket comms email mailboxes", Desc: "List mailboxes/folders"},
				{Command: "pocket comms slack channels", Desc: "List Slack channels"},
				{Command: "pocket comms slack messages", Desc: "Get channel messages", Args: "[channel]", Flags: "-l limit"},
				{Command: "pocket comms slack send", Desc: "Send Slack message", Args: "[message]", Flags: "-c channel"},
				{Command: "pocket comms discord guilds", Desc: "List Discord servers"},
				{Command: "pocket comms discord channels", Desc: "List guild channels", Args: "[guild-id]"},
				{Command: "pocket comms discord messages", Desc: "Get channel messages", Args: "[channel-id]", Flags: "-l limit"},
				{Command: "pocket comms discord send", Desc: "Send Discord message", Args: "[message]", Flags: "-c channel"},
				{Command: "pocket comms telegram chats", Desc: "List Telegram chats"},
				{Command: "pocket comms telegram messages", Desc: "Get chat messages", Args: "[chat-id]", Flags: "-l limit"},
				{Command: "pocket comms telegram send", Desc: "Send Telegram message", Args: "[message]", Flags: "-c chat"},
			},
		},
		{
			Name: "dev",
			Commands: []Cmd{
				{Command: "pocket dev github repos", Desc: "List repositories", Flags: "-l limit, -s sort, -u user"},
				{Command: "pocket dev github repo", Desc: "Get repo details", Args: "[owner/name]"},
				{Command: "pocket dev github issues", Desc: "List issues", Flags: "-r repo, -s state, -l limit, --labels"},
				{Command: "pocket dev github issue", Desc: "Get issue details", Args: "[owner/repo] [number]"},
				{Command: "pocket dev github prs", Desc: "List pull requests", Flags: "-r repo, -s state, -l limit"},
				{Command: "pocket dev github pr", Desc: "Get PR details", Args: "[owner/repo] [number]"},
				{Command: "pocket dev github notifications", Desc: "List notifications", Flags: "-l limit, -a all"},
				{Command: "pocket dev github search", Desc: "Search GitHub", Args: "[query]", Flags: "-t type, -l limit"},
				{Command: "pocket dev gitlab projects", Desc: "List projects", Flags: "-l limit"},
				{Command: "pocket dev gitlab issues", Desc: "List issues", Flags: "-p project, -s state, -l limit"},
				{Command: "pocket dev gitlab mrs", Desc: "List merge requests", Flags: "-p project, -s state, -l limit"},
				{Command: "pocket dev linear issues", Desc: "List Linear issues", Flags: "-t team, -s status, -l limit"},
				{Command: "pocket dev linear teams", Desc: "List Linear teams"},
				{Command: "pocket dev linear create", Desc: "Create Linear issue", Args: "[description]", Flags: "-t team, --title"},
				{Command: "pocket dev npm search", Desc: "Search npm packages", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket dev npm info", Desc: "Get package info", Args: "[package]"},
				{Command: "pocket dev npm versions", Desc: "List package versions", Args: "[package]", Flags: "-l limit"},
				{Command: "pocket dev npm deps", Desc: "List dependencies", Args: "[package]", Flags: "-d dev"},
				{Command: "pocket dev pypi search", Desc: "Search PyPI packages", Args: "[query]"},
				{Command: "pocket dev pypi info", Desc: "Get package info", Args: "[package]"},
				{Command: "pocket dev pypi versions", Desc: "List package versions", Args: "[package]", Flags: "-l limit"},
				{Command: "pocket dev pypi deps", Desc: "List dependencies", Args: "[package]"},
				{Command: "pocket dev gist list", Desc: "List your gists", Flags: "-l limit"},
				{Command: "pocket dev gist get", Desc: "Get gist details", Args: "[id]"},
				{Command: "pocket dev gist create", Desc: "Create a gist", Args: "[content]", Flags: "-d desc, -f filename, --public"},
				{Command: "pocket dev sentry projects", Desc: "List Sentry projects", Flags: "-l limit, -o org"},
				{Command: "pocket dev sentry issues", Desc: "List project issues", Args: "[project-slug]", Flags: "-l limit, -o org, -q query"},
				{Command: "pocket dev sentry issue", Desc: "Get issue details", Args: "[issue-id]"},
				{Command: "pocket dev sentry events", Desc: "List events for issue", Args: "[issue-id]", Flags: "-l limit"},
				{Command: "pocket dev redis get", Desc: "Get key value", Args: "[key]"},
				{Command: "pocket dev redis set", Desc: "Set key value", Args: "[key] [value]", Flags: "--ttl"},
				{Command: "pocket dev redis del", Desc: "Delete keys", Args: "[key...]"},
				{Command: "pocket dev redis keys", Desc: "List keys matching pattern", Args: "[pattern]", Flags: "-l limit"},
				{Command: "pocket dev redis info", Desc: "Get Redis server info"},
				{Command: "pocket dev prometheus query", Desc: "Instant PromQL query", Args: "[promql]"},
				{Command: "pocket dev prometheus range", Desc: "Range PromQL query", Args: "[promql]", Flags: "-s start, -e end, --step"},
				{Command: "pocket dev prometheus alerts", Desc: "List alerts", Flags: "--state"},
				{Command: "pocket dev prometheus targets", Desc: "List scrape targets", Flags: "--state"},
				{Command: "pocket dev kube pods", Desc: "List pods", Flags: "-n namespace, -a all"},
				{Command: "pocket dev kube logs", Desc: "Get pod logs", Args: "[pod]", Flags: "-n namespace, -t tail, -c container"},
				{Command: "pocket dev kube deployments", Desc: "List deployments", Flags: "-n namespace, -a all"},
				{Command: "pocket dev kube services", Desc: "List services", Flags: "-n namespace, -a all"},
				{Command: "pocket dev kube describe", Desc: "Describe a resource", Args: "[resource] [name]", Flags: "-n namespace"},
				{Command: "pocket dev db query", Desc: "Execute SQL query (read-only)", Args: "[db-path] [sql]", Flags: "-l limit"},
				{Command: "pocket dev db schema", Desc: "Show database schema", Args: "[db-path]"},
				{Command: "pocket dev db tables", Desc: "List tables", Args: "[db-path]"},
				{Command: "pocket dev s3 buckets", Desc: "List S3 buckets"},
				{Command: "pocket dev s3 ls", Desc: "List objects in bucket", Args: "[s3-path]", Flags: "-r recursive"},
				{Command: "pocket dev s3 get", Desc: "Download object", Args: "[s3-path] [local-path]"},
				{Command: "pocket dev s3 put", Desc: "Upload object", Args: "[local-path] [s3-path]"},
				{Command: "pocket dev s3 presign", Desc: "Generate presigned URL", Args: "[s3-path]", Flags: "--expires"},
			},
		},
		{
			Name: "productivity",
			Commands: []Cmd{
				{Command: "pocket productivity calendar events", Desc: "List upcoming events", Flags: "-d days, -l limit"},
				{Command: "pocket productivity calendar today", Desc: "List today's events"},
				{Command: "pocket productivity calendar create", Desc: "Create event", Flags: "--title, --start, --end, --desc"},
				{Command: "pocket productivity notion search", Desc: "Search Notion", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket productivity notion page", Desc: "Get page content", Args: "[page-id]"},
				{Command: "pocket productivity notion database", Desc: "Query database", Args: "[database-id]", Flags: "-l limit"},
				{Command: "pocket productivity todoist tasks", Desc: "List tasks", Flags: "-p project, -f filter"},
				{Command: "pocket productivity todoist projects", Desc: "List projects"},
				{Command: "pocket productivity todoist add", Desc: "Add a task", Args: "[content]", Flags: "-p project, -d due, --priority"},
				{Command: "pocket productivity todoist complete", Desc: "Complete a task", Args: "[task-id]"},
				{Command: "pocket productivity gsheets get", Desc: "Get spreadsheet info", Args: "[spreadsheet-id]"},
				{Command: "pocket productivity gsheets read", Desc: "Read cell values", Args: "[spreadsheet-id] [range]"},
				{Command: "pocket productivity gsheets search", Desc: "Search for value", Args: "[spreadsheet-id] [query]"},
				{Command: "pocket productivity gdrive search", Desc: "Search Drive files", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket productivity gdrive info", Desc: "Get file metadata", Args: "[file-id]"},
				{Command: "pocket productivity logseq graphs", Desc: "List configured graphs"},
				{Command: "pocket productivity logseq pages", Desc: "List pages in graph", Flags: "-g graph, -l limit"},
				{Command: "pocket productivity logseq read", Desc: "Read page content", Args: "[page]", Flags: "-g graph"},
				{Command: "pocket productivity logseq write", Desc: "Create/update page", Args: "[page] [content]", Flags: "-g graph, -a append"},
				{Command: "pocket productivity logseq search", Desc: "Search pages by content", Args: "[query]", Flags: "-g graph, -l limit, -c case-sensitive"},
				{Command: "pocket productivity logseq journal", Desc: "Get/create journal entry", Flags: "-g graph, -d date, -c content"},
				{Command: "pocket productivity logseq recent", Desc: "List recently modified pages", Flags: "-g graph, -l limit, -d days"},
			},
		},
		{
			Name: "news",
			Commands: []Cmd{
				{Command: "pocket news hn top", Desc: "HN top stories", Flags: "-l limit"},
				{Command: "pocket news hn new", Desc: "HN new stories", Flags: "-l limit"},
				{Command: "pocket news hn best", Desc: "HN best stories", Flags: "-l limit"},
				{Command: "pocket news hn ask", Desc: "Ask HN stories", Flags: "-l limit"},
				{Command: "pocket news hn show", Desc: "Show HN stories", Flags: "-l limit"},
				{Command: "pocket news hn item", Desc: "Get item with comments", Args: "[id]", Flags: "-c comments"},
				{Command: "pocket news feeds fetch", Desc: "Fetch RSS/Atom feed", Args: "[url]", Flags: "-l limit, -s summary-len"},
				{Command: "pocket news feeds list", Desc: "List saved feeds"},
				{Command: "pocket news feeds add", Desc: "Save a feed", Args: "[url]", Flags: "-n name"},
				{Command: "pocket news feeds read", Desc: "Fetch saved feed by name", Args: "[name]", Flags: "-l limit, -s summary-len"},
				{Command: "pocket news feeds remove", Desc: "Remove saved feed", Args: "[name-or-url]"},
				{Command: "pocket news newsapi headlines", Desc: "Get top headlines", Flags: "--country, --category, -l limit"},
				{Command: "pocket news newsapi search", Desc: "Search news", Args: "[query]", Flags: "--sort, -l limit"},
				{Command: "pocket news newsapi sources", Desc: "List news sources", Flags: "--category, --country"},
			},
		},
		{
			Name: "knowledge",
			Commands: []Cmd{
				{Command: "pocket knowledge wiki search", Desc: "Search Wikipedia", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket knowledge wiki summary", Desc: "Get article summary", Args: "[title]", Flags: "-s sentences"},
				{Command: "pocket knowledge wiki article", Desc: "Get full article", Args: "[title]", Flags: "-c chars"},
				{Command: "pocket knowledge so search", Desc: "Search StackOverflow", Args: "[query]", Flags: "-l limit, -t tagged, -s site"},
				{Command: "pocket knowledge so question", Desc: "Get question details", Args: "[id]", Flags: "-s site"},
				{Command: "pocket knowledge so answers", Desc: "Get answers", Args: "[question-id]", Flags: "-l limit, -s site"},
				{Command: "pocket knowledge dict define", Desc: "Get word definition", Args: "[word]", Flags: "-l limit"},
				{Command: "pocket knowledge dict synonyms", Desc: "Get synonyms", Args: "[word]"},
				{Command: "pocket knowledge dict antonyms", Desc: "Get antonyms", Args: "[word]"},
			},
		},
		{
			Name: "utility",
			Commands: []Cmd{
				{Command: "pocket utility weather now", Desc: "Current weather", Args: "[location]"},
				{Command: "pocket utility weather forecast", Desc: "Weather forecast", Args: "[location]", Flags: "-d days"},
				{Command: "pocket utility crypto price", Desc: "Get crypto prices", Args: "[coins...]"},
				{Command: "pocket utility crypto info", Desc: "Get coin details", Args: "[coin]"},
				{Command: "pocket utility crypto top", Desc: "Top coins by market cap", Flags: "-l limit"},
				{Command: "pocket utility crypto trending", Desc: "Trending coins"},
				{Command: "pocket utility crypto search", Desc: "Search for coins", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket utility ip me", Desc: "Get your public IP and location"},
				{Command: "pocket utility ip lookup", Desc: "Lookup IP geolocation", Args: "[ip]"},
				{Command: "pocket utility geocode forward", Desc: "Address to coordinates", Args: "[address]"},
				{Command: "pocket utility geocode reverse", Desc: "Coordinates to address", Args: "[lat] [lon]"},
				{Command: "pocket utility timezone get", Desc: "Get time in timezone", Args: "[timezone]"},
				{Command: "pocket utility timezone ip", Desc: "Get timezone by IP", Args: "[ip]"},
				{Command: "pocket utility timezone list", Desc: "List all timezones"},
				{Command: "pocket utility paste create", Desc: "Create a paste", Args: "[content]", Flags: "-e expiry, -t title"},
				{Command: "pocket utility paste get", Desc: "Fetch a paste", Args: "[url]"},
				{Command: "pocket utility netdiag headers", Desc: "Get HTTP response headers", Args: "[url]"},
				{Command: "pocket utility netdiag ports", Desc: "Scan common ports", Args: "[host]", Flags: "-t timeout"},
				{Command: "pocket utility netdiag ping", Desc: "DNS resolve and timing", Args: "[host]"},
				{Command: "pocket utility domain whois", Desc: "WHOIS lookup for domain", Args: "[domain]"},
				{Command: "pocket utility domain dns", Desc: "DNS records for domain", Args: "[domain]", Flags: "-t type"},
				{Command: "pocket utility currency convert", Desc: "Convert between currencies", Args: "[amount] [from] [to]"},
				{Command: "pocket utility currency rates", Desc: "Get exchange rates", Args: "[base]", Flags: "-l limit"},
				{Command: "pocket utility wayback lookup", Desc: "Look up Wayback Machine snapshots", Args: "[url]"},
				{Command: "pocket utility holidays list", Desc: "List holidays for a country", Flags: "-c country, -y year"},
				{Command: "pocket utility translate text", Desc: "Translate text", Args: "[text]", Flags: "-f from, -t to"},
				{Command: "pocket utility stocks quote", Desc: "Get stock quote", Args: "[symbol]"},
				{Command: "pocket utility stocks search", Desc: "Search stocks", Args: "[query]"},
				{Command: "pocket utility urlshort shorten", Desc: "Shorten a URL", Args: "[url]"},
				{Command: "pocket utility speedtest run", Desc: "Full speed test (download, upload, latency)", Flags: "--size"},
				{Command: "pocket utility speedtest download", Desc: "Download speed test only", Flags: "--size"},
				{Command: "pocket utility speedtest upload", Desc: "Upload speed test only", Flags: "--size"},
				{Command: "pocket utility speedtest latency", Desc: "Latency test only", Flags: "--count"},
				{Command: "pocket utility dnsbench run", Desc: "Benchmark all DNS resolvers"},
				{Command: "pocket utility dnsbench test", Desc: "Test a specific DNS resolver", Args: "[resolver-ip]"},
				{Command: "pocket utility traceroute run", Desc: "Trace network path to host", Args: "[host]", Flags: "--max-hops"},
				{Command: "pocket utility wifi scan", Desc: "Scan nearby WiFi networks"},
				{Command: "pocket utility wifi current", Desc: "Show current WiFi connection"},
			},
		},
		{
			Name: "security",
			Commands: []Cmd{
				{Command: "pocket security virustotal url", Desc: "Scan a URL", Args: "[url]"},
				{Command: "pocket security virustotal domain", Desc: "Get domain report", Args: "[domain]"},
				{Command: "pocket security virustotal ip", Desc: "Get IP report", Args: "[ip]"},
				{Command: "pocket security virustotal hash", Desc: "Get file hash report", Args: "[hash]"},
				{Command: "pocket security shodan lookup", Desc: "Lookup IP (ports, vulns)", Args: "[ip]"},
				{Command: "pocket security crtsh lookup", Desc: "Certificate transparency lookup", Args: "[domain]", Flags: "-l limit, --expired"},
				{Command: "pocket security hibp password", Desc: "Check password in breaches", Args: "[password]"},
				{Command: "pocket security hibp breaches", Desc: "List public data breaches", Flags: "-l limit"},
			},
		},
		{
			Name: "marketing",
			Commands: []Cmd{
				{Command: "pocket marketing facebook-ads account", Desc: "Get ad account details"},
				{Command: "pocket marketing facebook-ads campaigns", Desc: "List campaigns", Flags: "-s status, -l limit"},
				{Command: "pocket marketing facebook-ads campaign-create", Desc: "Create a campaign", Flags: "--name, --objective, --status, --daily-budget, --special-categories"},
				{Command: "pocket marketing facebook-ads campaign-update", Desc: "Update a campaign", Args: "[campaign-id]", Flags: "--name, --status, --daily-budget"},
				{Command: "pocket marketing facebook-ads adsets", Desc: "List ad sets", Flags: "-c campaign-id, -s status, -l limit"},
				{Command: "pocket marketing facebook-ads adset-create", Desc: "Create an ad set", Flags: "--name, --campaign-id, --billing-event, --optimization-goal"},
				{Command: "pocket marketing facebook-ads ads", Desc: "List ads", Flags: "--adset-id, -s status, -l limit"},
				{Command: "pocket marketing facebook-ads insights", Desc: "Get performance insights", Flags: "--object-id, --date-start, --date-stop, --level, -f fields"},
				{Command: "pocket marketing amazon-sp orders", Desc: "List orders", Flags: "-s status, --after, --before, --marketplace, -l limit"},
				{Command: "pocket marketing amazon-sp order", Desc: "Get order details", Args: "[order-id]"},
				{Command: "pocket marketing amazon-sp order-items", Desc: "Get items for an order", Args: "[order-id]"},
				{Command: "pocket marketing amazon-sp inventory", Desc: "List FBA inventory", Flags: "--sku, --marketplace, -l limit"},
				{Command: "pocket marketing amazon-sp report-create", Desc: "Create a report request", Flags: "--type, --start, --end, --marketplace"},
				{Command: "pocket marketing amazon-sp report-status", Desc: "Get report status", Args: "[report-id]"},
				{Command: "pocket marketing shopify shop", Desc: "Get store info"},
				{Command: "pocket marketing shopify orders", Desc: "List orders", Flags: "-l limit, --status, --since, --financial"},
				{Command: "pocket marketing shopify order", Desc: "Get order details", Args: "[id]"},
				{Command: "pocket marketing shopify products", Desc: "List products", Flags: "-l limit, --status, --vendor, --collection"},
				{Command: "pocket marketing shopify product", Desc: "Get product details", Args: "[id]"},
				{Command: "pocket marketing shopify customers", Desc: "List customers", Flags: "-l limit"},
				{Command: "pocket marketing shopify customer-search", Desc: "Search customers", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket marketing shopify inventory", Desc: "List inventory levels", Flags: "--location, -l limit"},
				{Command: "pocket marketing shopify inventory-set", Desc: "Set inventory level", Flags: "--item, --location, --available"},
			},
		},
		{
			Name: "setup",
			Commands: []Cmd{
				{Command: "pocket setup list", Desc: "List services needing setup", Flags: "-a all"},
				{Command: "pocket setup show", Desc: "Show setup instructions", Args: "[service]"},
				{Command: "pocket setup set", Desc: "Set credential for service", Args: "[service] [key] [value]"},
			},
		},
		{
			Name: "config",
			Commands: []Cmd{
				{Command: "pocket config path", Desc: "Show config file path"},
				{Command: "pocket config list", Desc: "List all config (redacted)"},
				{Command: "pocket config set", Desc: "Set a config value", Args: "[key] [value]"},
				{Command: "pocket config get", Desc: "Get a config value", Args: "[key]"},
			},
		},
		{
			Name: "system",
			Commands: []Cmd{
				{Command: "pocket system clipboard get", Desc: "Get clipboard content", Flags: "-m max-length, -r raw"},
				{Command: "pocket system clipboard set", Desc: "Set clipboard content", Args: "[text]"},
				{Command: "pocket system clipboard clear", Desc: "Clear clipboard"},
				{Command: "pocket system clipboard copy", Desc: "Copy file to clipboard", Args: "[file]"},
				{Command: "pocket system clipboard history", Desc: "Clipboard history info"},
				{Command: "pocket system notes list", Desc: "List all notes", Flags: "-f folder, -l limit"},
				{Command: "pocket system notes folders", Desc: "List all folders"},
				{Command: "pocket system notes read", Desc: "Read a note by name", Args: "[name]", Flags: "-f folder"},
				{Command: "pocket system notes create", Desc: "Create a new note", Args: "[name] [body]", Flags: "-f folder"},
				{Command: "pocket system notes search", Desc: "Search notes", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket system notes append", Desc: "Append text to note", Args: "[name] [text]", Flags: "-f folder"},
				{Command: "pocket system mail accounts", Desc: "List mail accounts"},
				{Command: "pocket system mail mailboxes", Desc: "List mailboxes/folders", Flags: "-a account"},
				{Command: "pocket system mail list", Desc: "List recent messages", Flags: "-m mailbox, -a account, -l limit, -u unread"},
				{Command: "pocket system mail read", Desc: "Read a message by ID", Args: "[id]"},
				{Command: "pocket system mail search", Desc: "Search messages", Args: "[query]", Flags: "-l limit, -m mailbox, -a account"},
				{Command: "pocket system mail send", Desc: "Send an email", Flags: "--to, --subject, --body, --cc, --bcc, -a account"},
				{Command: "pocket system mail unread", Desc: "List unread messages", Flags: "-l limit, -a account"},
				{Command: "pocket system mail count", Desc: "Get unread message count", Flags: "-a account"},
				{Command: "pocket system safari tabs", Desc: "List all open tabs", Flags: "-w window"},
				{Command: "pocket system safari url", Desc: "Get URL of current tab", Flags: "-w window, -t tab"},
				{Command: "pocket system safari title", Desc: "Get title of current tab"},
				{Command: "pocket system safari open", Desc: "Open URL in new tab", Args: "[url]", Flags: "-n new-window"},
				{Command: "pocket system safari close", Desc: "Close current tab", Flags: "-w window, -t tab, --window-close"},
				{Command: "pocket system safari bookmarks", Desc: "List bookmarks", Flags: "-f folder, -l limit"},
				{Command: "pocket system safari reading-list", Desc: "List Reading List items", Flags: "-l limit"},
				{Command: "pocket system safari add-reading", Desc: "Add URL to Reading List", Args: "[url]", Flags: "-t title"},
				{Command: "pocket system safari history", Desc: "Get recent history", Flags: "-l limit, -d days, -s search"},
				{Command: "pocket system calendar events", Desc: "List upcoming events", Flags: "-d days, -l limit"},
				{Command: "pocket system calendar today", Desc: "List today's events"},
				{Command: "pocket system calendar create", Desc: "Create event", Flags: "--title, --start, --end, --desc"},
				{Command: "pocket system contacts list", Desc: "List contacts", Flags: "-l limit, -g group"},
				{Command: "pocket system contacts search", Desc: "Search contacts", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket system finder info", Desc: "File/folder metadata", Args: "[path]"},
				{Command: "pocket system finder search", Desc: "Search with Spotlight", Args: "[query]", Flags: "-l limit, -d dir"},
				{Command: "pocket system finder recent", Desc: "Recently modified files", Flags: "-l limit, -d dir"},
				{Command: "pocket system finder tags", Desc: "Get/set Finder tags", Args: "[path]"},
				{Command: "pocket system imessage list", Desc: "List recent conversations", Flags: "-l limit"},
				{Command: "pocket system imessage read", Desc: "Read messages from chat", Args: "[chat-id]", Flags: "-l limit"},
				{Command: "pocket system imessage search", Desc: "Search messages", Args: "[query]", Flags: "-l limit"},
				{Command: "pocket system reminders list", Desc: "List reminders", Flags: "-l limit, --list"},
				{Command: "pocket system reminders lists", Desc: "List reminder lists"},
				{Command: "pocket system reminders create", Desc: "Create a reminder", Args: "[title]", Flags: "--list, --due, --notes"},
				{Command: "pocket system sysinfo overview", Desc: "System overview (CPU, memory, disk, uptime)"},
				{Command: "pocket system sysinfo cpu", Desc: "CPU info and load averages"},
				{Command: "pocket system sysinfo memory", Desc: "Memory usage details"},
				{Command: "pocket system sysinfo disk", Desc: "Disk usage per mount"},
				{Command: "pocket system sysinfo processes", Desc: "Top processes by CPU/memory", Flags: "-l limit"},
				{Command: "pocket system sysinfo network", Desc: "Network interfaces and IPs"},
				{Command: "pocket system battery status", Desc: "Current battery charge and state"},
				{Command: "pocket system battery health", Desc: "Battery health, cycle count, capacity"},
				{Command: "pocket system diskhealth status", Desc: "Disk health and S.M.A.R.T. overview"},
				{Command: "pocket system diskhealth info", Desc: "Detailed disk info", Args: "[disk]"},
				{Command: "pocket system cleanup scan", Desc: "Full scan of cleanable directories (read-only)"},
				{Command: "pocket system cleanup caches", Desc: "Scan cache directories only"},
				{Command: "pocket system cleanup logs", Desc: "Scan log directories only"},
				{Command: "pocket system cleanup temp", Desc: "Scan temp directories only"},
			},
		},
	}
}
